Ext.define('APP.view.sd.sales.care.data',{
    extend:'Ext.grid.Panel',
    controller:'sd.sales',
	store:{
		autoLoad:true,
		type:'sales.data',
		//type:'sales.userData',
		proxy:{extraParams:{app:'care'}}
	},
	dockedItems:[
		{dock:'top',xtype:'toolbar',items:[
			{xtype:'segmentedfield',segmented:{
				name:'type',
				value:'',
				defaults:{minWidth:60},
				items:[
					{text:'IB',value:'ib'},
					{text:'IBC',value:'ibc'},
					{text:'SH',value:'sh'},
					{text:'ALL',value:''}
				]
			}},'-',
			{xtype:'searchbar',
				fields:[
					{xtype:'fieldSalesTrack',segmented:{name:'track',value:''}},
					{emptyText:'评星...',xtype:'comboRating',name:'rating',width:100},
					{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
				]
			},
			'->',
			{xtype:'refreshbutton'}
		]},
		{dock:'bottom',xtype:'pagingbar'}
	],
	columns:[
		{xtype:'rownumberer'},
		{text:'客户信息',defaults:{sortable:true,width:130},columns:[
			{text:'客户',xtype:'templatecolumn',tpl:'{name:nullToNA}<r>{mobile:safeMobile}</r>',width:180},
			{text:'账号',xtype:'templatecolumn',tpl:'<b>{login}</b><r>{type}</r>',width:120},
			{text:'区域',xtype:'templatecolumn',dataIndex:'province',tpl:'{province} {city}',width:120},
			{text:'活跃日期',xtype:'datecolumn',dataIndex:'lastdate',format:'Y-m-d',width:100}
		]},
		{text:'出入金',defaults:{sortable:true},columns:[
			{text:'入金',dataIndex:'funds_deposit',width:100,tdCls:'x-ui-text-green',align:'right',renderer:'returnShowMoney'},
			{text:'出金',dataIndex:'funds_withdrawal',width:100,tdCls:'x-ui-text-red',align:'right',renderer:'returnShowMoney'},
			{text:'净入金',dataIndex:'funds_net_deposit',width:100,tdCls:'x-ui-text-blue',align:'right',renderer:'returnShowMoney'}
		]},
		{text:'跟进记录',defaults:{sortable:true},columns:[
			{text:'已跟进',dataIndex:'track_day',width:88,renderer:'returnSalesCareTrackHistory'},
			{text:'通话时长',dataIndex:'call_duration',width:100,renderer:'returnResCall'},
			{text:'最新状态',dataIndex:'track_time',width:100,renderer:'returnSalesCareTrackTime'}
		]},
		{text:'备注',dataIndex:'explain',minWidth:140,flex:1,renderer:'returnMore'}
	],
	listeners:{
		itemdblclick:'onDataShowDetail'
	}
});
