Ext.define('APP.view.rd.analysis.account.trend',{
    extend:'Ext.Panel',
    controller:'rd',
	layout:{type:'border',align:'stretch',padding:3},
	defaults:{xtype:'panel',layout:'fit',split:true,border:true},
	dockedItems:[
		{dock:'top',xtype:'toolbar',items:[
			{xtype:'searchbar',
				fields:[
					{xtype:'datepartfield',name:'datepart',value:'month',allowBlank:false},
					{emptyText:'账号...',xtype:'numberfield',vtype:'login',name:'login',width:140}
				]
			},
			'->',
			{xtype:'refreshbutton'}
		]}
	],
	items:[
		{xtype:'grid',region:'west',iconCls:'f-mt mt-grid',width:500,maxWidth:1000,collapsible:true,title:'数据报表',
			store:{
				type:'analysis.trade.trend',
				autoLoad:false,
				sorters:[{property:'objects',direction:'ASC'}],
				proxy:{
					extraParams:{
						datepart:'month',
						startdate:Ext.Date.format(Ext.Date.add(new Date(),Ext.Date.MONTH,-5),'Y-m'),
						enddate:Ext.Date.format(new Date(),'Y-m')
					}
				}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',
					items:[
						'->',
						{xtype:'reconfigurebutton',
							items:[
								{text:'开户量',value:'account',pressed:true},
								{text:'出入金',value:'funds'},
								{text:'佣金',value:'commission'},
								{text:'交易盈亏',value:'trade'}
							]
						},
						'->'
					]
				}
			],
			multiSelect:false,
			config:{
				columns:{
					account:[
						{xtype:'rownumberer'},
						{text:'时间',dataIndex:'objects',minWidth:80,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'IB',dataIndex:'account_new_count_ib',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'IBC',dataIndex:'account_new_count_ibc',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'SH',dataIndex:'account_new_count_sh',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'小计',dataIndex:'account_new_count',tdCls:'x-ui-active',align:'right',width:100,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'}
					],
					funds:[
						{xtype:'rownumberer'},
						{text:'时间',dataIndex:'objects',minWidth:80,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'入金',dataIndex:'funds_deposit',tdCls:'x-ui-text-green',align:'right',width:110,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'出金',dataIndex:'funds_withdrawal',tdCls:'x-ui-text-red',align:'right',width:110,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'净入金',dataIndex:'funds_net_deposit',tdCls:'x-ui-active x-ui-text-blue',align:'right',width:110,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'}
					],
					commission:[
						{xtype:'rownumberer'},
						{text:'时间',dataIndex:'objects',minWidth:80,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'交易量',dataIndex:'trade_volume',tdCls:'x-ui-text-bold',align:'right',width:80,renderer:'returnNumber',summaryType:'sum',summaryRenderer:'returnNumber'},
						{text:'内佣',dataIndex:'trade_commission_internal',tdCls:'x-ui-text-green',align:'right',width:90,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'外佣',dataIndex:'trade_commission_foreign',tdCls:'x-ui-text-red',align:'right',width:90,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'小计',dataIndex:'trade_commission_agent',tdCls:'x-ui-active x-ui-text-blue',align:'right',width:100,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'}
					],
					trade:[
						{xtype:'rownumberer'},
						{text:'时间',dataIndex:'objects',minWidth:80,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'交易量',dataIndex:'trade_volume',tdCls:'x-ui-text-bold',align:'right',width:80,renderer:'returnNumber',summaryType:'sum',summaryRenderer:'returnNumber'},
						{text:'利息',dataIndex:'trade_storage',align:'right',width:80,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'税金',dataIndex:'trade_taxes',align:'right',width:80,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney',hidden:true},
						{text:'交易盈亏',dataIndex:'trade_profit',align:'right',width:100,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'},
						{text:'净盈亏',dataIndex:'trade_clear',tdCls:'x-ui-active x-ui-text-blue',align:'right',width:100,renderer:'returnShowMoney',summaryType:'sum',summaryRenderer:'returnShowMoney'}
					]
				}
			},
			features:[{ftype:'summary',dock:'bottom'}],
			listeners:{
				sortchange:'onMateGridChartSortChange',
				selectionchange:'onMateGridChartSelectionChange'
			}
		},
		{xtype:'mate.chart',mateParameters:{
			type:'trend',
			menu:{
				account:{
					checked:3,
					items:[
						{text:'IB',field:'account_new_count_ib',title:'账户·新开账户趋势·IB'}, 
						{text:'IBC',field:'account_new_count_ibc',title:'账户·新开账户趋势·IBC'}, 
						{text:'SH',field:'account_new_count_sh',title:'账户·新开账户趋势·SH'}, 
						{text:'开户量',field:'account_new_count',title:'账户·新开账户趋势'}
					]
				},
				funds:{
					checked:2,
					items:[
						{text:'入金',field:'funds_deposit',title:'账户·入金趋势'}, 
						{text:'出金',field:'funds_withdrawal',title:'账户·出金趋势'}, 
						{text:'净入金',field:'funds_net_deposit',title:'账户·净入金趋势'}
					]
				},
				commission:{
					checked:1,
					items:[
						{text:'交易量',field:'trade_volume',title:'账户·代理交易量趋势'}, 
						{text:'内佣',field:'trade_commission_internal',title:'账户·内佣趋势'},
						{text:'外佣',field:'trade_commission_foreign',title:'账户·外佣趋势'},
						{text:'小计',field:'trade_commission_agent',title:'账户·佣金趋势'}
					]
				},
				trade:{
					checked:4,
					items:[
						{text:'交易量',field:'trade_volume',title:'账户·交易量趋势'}, 
						{text:'利息',field:'trade_storage',title:'账户·交易利息趋势'},
						{text:'税金',field:'trade_taxes',title:'账户·交易税金趋势',hidden:true},
						{text:'交易盈亏',field:'trade_profit',title:'账户·交易盈亏趋势'}, 
						{text:'净盈亏',field:'trade_clear',title:'账户·净盈亏趋势'}
					]
				}
			}
		}}
	]
});

