Ext.define('APP.view.ia.account.change.update',{
    extend:'Ext.Panel',
	controller:'ia.account.change',
	layout:{type:'border',align:'stretch',padding:3},
	viewModel:true,
	defaults:{split:false,border:true},
	items:[
		{xtype:'grid',region:'center',title:'账户',flex:.5,
			reference:'waitGrid',
			store:{
				type:'account.manager',
				autoLoad:true,
				remoteSort:true,
				pageSize:100,
				sorters:[{property:'regdate',direction:'ASC'}],
				grouper:false,			
				proxy:{extraParams:{menu:'effective'}}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'组...',xtype:'comboAccountGroup',multiSelect:true},
							{emptyText:'销售...',xtype:'comboCompanyStaff',root:103,name:'salesmanid',width:140,multiSelect:true},
							{emptyText:'账号/代理...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]},
				{dock:'bottom',xtype:'pagingbar'}
			],
			forceFit:true,
			selType:'checkboxmodel',
			columns:[
				//{xtype:'rownumberer'},
				{text:'账号',dataIndex:'login',minWidth:140,renderer:'returnLogin',summaryType:'count'},
				{text:'开户日期',dataIndex:'regdate',xtype:'datecolumn',width:100},
				{text:'上级代理',dataIndex:'agent',width:140,renderer:'returnAgentAccount'},
				{text:'账户权限',dataIndex:'role_name',width:100,hidden:true},					
				{text:'账户性质',dataIndex:'property_name',width:100,hidden:true},					
				{text:'组',dataIndex:'group',width:100},					
				//{text:'杠杆',dataIndex:'leverage',width:70,align:'center',renderer:'returnLeverage',hidden:true},
				{text:'销售',dataIndex:'salesman_namecn',width:100,renderer:'returnSalesman'}
			],
			//features:[{ftype:'summary',dock:'bottom'}],
			listeners:{
				itemdblclick:'onMateGridRecordToRight'
			}
	   	},
		{region:'east',xtype:'toolbar',dock:'right',split:false,flex:0,margin:'0 3',
			items:[
				'->',
				{iconCls:'f-mt mt-outline-right',scale:'large',bind:{disabled:'{!waitGrid.selection}'},handler:'onMateGridRecordBatchToRight'},
				' ',
				{iconCls:'f-mt mt-outline-left',scale:'large',bind:{disabled:'{!beingGrid.selection}'},handler:'onMateGridRecordBatchToLeft'},
				'->'
			]
		},
		{xtype:'grid',region:'east',title:'待更新的账户',flex:.5,collapsible:true,
			reference:'beingGrid',
			store:{			
				autoLoad:false,
				remoteSort:false,
				model:'APP.model.account.record',
				sorters:[{property:'login',direction:'ASC'}]
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					'->',
					{iconCls:'f-mt mt-action-update',text:'更新',handler:'onAccountBatchUpdateClick'}
				]}
			],
			forceFit:true,
			//selType:'checkboxmodel',
			columns:[
				{xtype:'rownumberer'},
				{text:'账号',dataIndex:'login',minWidth:140,renderer:'returnLogin',summaryType:'count'},
				{text:'开户日期',dataIndex:'regdate',xtype:'datecolumn',width:100},
				{text:'上级代理',dataIndex:'agent',width:140,renderer:'returnAgentAccount'},
				{text:'账户权限',dataIndex:'role_name',width:100,hidden:true},					
				{text:'账户性质',dataIndex:'property_name',width:100,hidden:true},					
				{text:'组',dataIndex:'group',width:100},					
				//{text:'杠杆',dataIndex:'leverage',width:70,align:'center',renderer:'returnLeverage',hidden:true},
				{text:'销售',dataIndex:'salesman_namecn',width:100,renderer:'returnSalesman'}
			],
			features:[{ftype:'summary',dock:'bottom'}],
			listeners:{
				itemdblclick:'onMateGridRecordToLeft'
			}
		}		
	]
});
