Ext.define('APP.view.rd.shouting.skill.callFrom',{
    extend:'Ext.form.Panel',
	xtype:'rdShoutingSKillCallFrom',
    controller:'rd.shouting.skill',
	width:850,
	items:[
		{title:'喊单信息',fieldDefaults:{allowBlank:false},items:[
			{columnWidth:.55,items:[
				{fieldLabel:'商品',xtype:'textfield',name:'symbol'},
				{xtype:'fieldcontainer',layout:'hbox',items:[
					{fieldLabel:'时间',xtype:'datefield',name:'date',flex:.5},
					{fieldLabel:'进场点位',xtype:'numberfield',name:'entry_price',flex:.5,margin:'0 0 0 5'}
				]},
				{xtype:'fieldcontainer',layout:'hbox',items:[
					{fieldLabel:'周期',xtype:'combo',
						store:{
							fields:['value','display'],
							data:[
								['M1','M1'],
								['M5','M5'],
								['M15','M15'],
								['M30','M30'],
								['H1','H1'],
								['H4','H4'],
								['D1','D1'],
								['W1','W1'],
								['MN','MN']
							]
						},
						emptyText:'周期',
						width:120,
						name:'cycle',
						valueField:'value',
						displayField:'display',
						flex:.5
					},
					{fieldLabel:'方向',xtype:'combo',
						store:{
							fields:['value','display'],
							data:[
								[1,'多'],
								[0,'空']
							]
						},
						emptyText:'方向...',
						width:120,
						name:'cmd',
						valueField:'value',
						displayField:'display',
					flex:.5,margin:'0 0 0 5'}
				]},
				{xtype:'fieldcontainer',layout:'hbox',items:[
					{fieldLabel:'止损',xtype:'numberfield',name:'sl',allowBlank:true,flex:.5},
					{fieldLabel:'止盈',xtype:'numberfield',name:'tp',allowBlank:true,flex:.5,margin:'0 0 0 5'}
				]},
				{fieldLabel:'技术点评',xtype:'textarea',name:'explain',height:50,emptyText:'技术点评'},
				{xtype:'fieldcontainer',fieldLabel:'控制项',items:[
					{xtype:'checkbox',boxLabel:'显示',name:'locked'}
				]}
			]},
			{columnWidth:.45,items:[
				{xtype:'fieldcontainer',fieldLabel:'图片',items:[
					{xtype:'uploadimagefield',mateParameters:{title:'上传 图片',name:'image',height:200}}
				]}
			]}
		]},
		{title:'喊单结果',hidden:true,bind:{hidden:'{!isUpdate}'},items:[
			{columnWidth:.55,items:[{fieldLabel:'开仓价',xtype:'numberfield',name:'open_price'}]},
			{columnWidth:.45,items:[{fieldLabel:'平仓价',xtype:'numberfield',name:'close_price'}]},
			{columnWidth:.55,items:[{fieldLabel:'结果',xtype:'combo',
				store:{fields:['value','display'],data:[[0,'持仓中'],[1,'已平仓'],[2,'未进场']]},
				emptyText:'结果',
				name:'result',
				valueField:'value',
				displayField:'display'
			}]},
			{columnWidth:.45,items:[{fieldLabel:'盈亏点数',xtype:'numberfield',name:'profit_point'}]}
		]}
	]
});
