Ext.define('APP.view.rd.shouting.skill.tc',{
    extend:'Ext.Container',
	controller:'rd.shouting.skill',
	layout:{type:'border',align:'stretch',padding:3},
	items:[
		{xtype:'panel',region:'west',collapsible:false,split:true,
			layout:{type:'vbox',align:'stretch'},
			width:240,
			minWidth:240,
			maxWidth:320,
			items:[
				{xtype:'menu',title:'分类检索',
					floating:false,
					userCls:'x-ui-nav-menu',
					defaults:{iconCls:'f-mt mt-right-arrow'},
					listeners:{click:'onMateMenuReloadStore'},
					items:[
						{text:'外汇',params:{type:'DEVISES'}},
						{text:'指数',params:{type:'INDICES'}},
						{text:'股票',params:{type:'ACTIONS'}},
						{text:'债券',params:{type:'TAUX'}},
						{text:'商品',params:{type:'COMMODITIES'}},
						{text:'全部',params:{type:''},userCls:'x-menu-item-selected'}
					]
				}
			]
		},
		{xtype:'grid',region:'center',
			store:{
				autoLoad:true,
				type:'rdShoutingSkillTc',
				proxy:{
					extraParams:{language:'zh_cn'}
				}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{xtype:'segmentedfield',segmented:{
								name:'language',
								items:[
									{text:'中文',value:'zh_cn',pressed:true},
									{text:'英文',value:'en'}
								]
							}},
							{emptyText:'日期从',xtype:'startdatefield',name:'startdate'},
							{emptyText:'日期至',xtype:'enddatefield',name:'enddate'},
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:200}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]},
				{dock:'bottom',xtype:'pagingbar'}
			],
			//forceFit:true,
			columns:[
				{xtype:'rownumberer'},
				{text:'时间',dataIndex:'time',xtype:'datecolumn',format:'Y-m-d H:00',hidden:true},
				{text:'时间',dataIndex:'time',xtype:'datecolumn',format:'H:i',width:100},
				{text:'分类',dataIndex:'type',renderer:'returnTcType',width:140,hidden:true},
				{text:'交易代码',dataIndex:'ticker',width:140},
				{text:'交易品种',dataIndex:'symbol',width:260},
				//{text:'图',dataIndex:'image',width:140,renderer:'returnChart'},
				{text:'每日变动',dataIndex:'daily',width:100,renderer:'returnTcDaily'},
				{text:'每周变动',dataIndex:'weekly',width:100,renderer:'returnTcWeekly'},
				{text:'标题',dataIndex:'title',flex:1,renderer:'returnTcTitle'}
			],
			features:[{ftype:'grouping'}],
			listeners:{
				itemdblclick:'onTcDetail'
			}
		}
	]
});