Ext.define('APP.view.hr.staff.change.reinstatement',{
    extend:'Ext.Container',
    controller:'hr.staff.change',
	layout:{type:'border',align:'stretch',padding:3},
	defaults:{split:true},
	items:[
		{xtype:'grid',region:'west',title:'待复职员工',collapsible:true,width:600,
			reference:'gridBase',
			store:{
				type:'hrStaff',
				autoLoad:true,
				pageSize:false,
				sorters:[{property:'enddate',direction:'DESC'}],
				proxy:{
					extraParams:{invalid:1}
				}	
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]}
			],
			columns:[
				{xtype:'rownumberer',width:34},
				{text:'ID',dataIndex:'id',width:80,hidden:true},
				{text:'姓名',xtype:'templatecolumn',dataIndex:'namecn',minWidth:180,flex:1,tpl:'{namecn} <s>{name}</s> <r>{post_name}</r>',summaryType:'count'},
				{text:'工号',dataIndex:'login',width:100,renderer:'returnLogin'},
				{text:'任职部门',xtype:'templatecolumn',dataIndex:'departmentid',width:100,tpl:'{department_name}'},
				{text:'原属团队',xtype:'templatecolumn',dataIndex:'teamid',width:160,tpl:'{team_name}<r>{manager_namecn}</r>'},
				{text:'离职日期',dataIndex:'enddate',width:80}
			],
			viewConfig:{enableTextSelection:false},
			features:[{ftype:'grouping'},{ftype:'summary',dock:'bottom'}],
			listeners:{
				itemdblclick:'onChangeReinstatementClick'
			}
	   	},
		{xtype:'grid',region:'center',title:'复职记录',
			reference:'gridChange',
			store:{
				type:'cross',
				autoLoad:true,
				fields:[
					{name:'creattime',type:'date'}
				],
				sorters:[{property:'id',direction:'DESC'}],
				groupField:'date',
				groupDir:'DESC',
				proxy:{
					url:Boot.appUrl('/hr/staff/change/getLeaving.do'),
					extraParams:{leaving:0},
				}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'离职月份...',xtype:'monthfield',name:'month'},
							{emptyText:'员工...',xtype:'comboCompanyStaff',name:'staffid'},
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]},
				{dock:'bottom',xtype:'pagingbar'}
			],
			columns:[
				{xtype:'rownumberer'},
				{text:'ID',dataIndex:'id',width:80,hidden:true},
				{text:'姓名',xtype:'templatecolumn',dataIndex:'namecn',minWidth:180,flex:1,tpl:'{namecn} <s>{name}</s> <r>{post_name}</r>',summaryType:'count'},
				{text:'工号',dataIndex:'login',width:100,renderer:'returnLogin'},
				{text:'任职部门',xtype:'templatecolumn',dataIndex:'departmentid',width:100,tpl:'{department_name}'},
				{text:'现属团队',xtype:'templatecolumn',dataIndex:'teamid',width:160,tpl:'{team_name}<r>{post_name}</r>'},
				{text:'手机',dataIndex:'mobile',width:120},
				{text:'QQ',dataIndex:'qq',width:60,align:'center',renderer:'returnQQ'},
				{text:'复职日期',dataIndex:'date',width:100},
				{text:'操作时间',dataIndex:'creattime',xtype:'datecolumn',format:'Y-m-d H:i A',width:160},
				{text:'操作人',dataIndex:'operator',width:80}
			],
			features:[{ftype:'grouping'}]
		}		
	]
});
