Ext.define('APP.view.sd.mgr.call.change.allot',{
    extend:'Ext.Panel',
    controller:'sd.call.change',
	layout:{type:'border',align:'stretch',padding:3},
	defaults:{split:false,border:true},
	items:[
		{xtype:'grid',region:'west',title:'号码库存',width:680,
			reference:'gridBase',
			store:{
				type:'call.storage',
				autoLoad:true
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]}
			],
			multiSelect:false,
			columns:[
				{xtype:'rownumberer'},
				{text:'号码',dataIndex:'no',minWidth:100,flex:1,summaryType:'count'},
				{text:'开户日期',xtype:'datecolumn',dataIndex:'opendate',format:'Y-m-d',width:88},
				{text:'总量',dataIndex:'voice_addupupper',width:100,align:'right',renderer:'returnInt'},
				{text:'已用',dataIndex:'voice_used',tdCls:'x-ui-text-green',width:100,align:'right',renderer:'returnInt'},
				{text:'剩余',dataIndex:'voice_canuse',tdCls:'x-ui-text-red',width:100,align:'right',renderer:'returnInt'},
				{text:'累计通话',dataIndex:'duration',width:100,align:'right',renderer:'returnTimeFilter'}
			],
			viewConfig:{enableTextSelection:false},
			features:[{ftype:'summary',dock:'bottom'}],
			listeners:{
				itemdblclick:'onAllotClick'
			}
	   	},
		{xtype:'grid',region:'center',title:'分配记录',margin:'0 0 0 3',
			reference:'gridChange',
			store:{
				type:'call.change.staff',
				autoLoad:true,
				proxy:{extraParams:{idx:'ALLOT'}}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',fields:[
						{emptyText:'分配予...',xtype:'comboCompanyStaff',name:'after'},
						{xtype:'textfield',name:'query',width:140,emptyText:'关键字...'}
					]},
					'->',
					{xtype:'refreshbutton'}
				]},
				{dock:'bottom',xtype:'pagingbar'}
			],
			columns:[
				{xtype:'rownumberer'},
				{text:'号码',dataIndex:'no',minWidth:100,flex:1,summaryType:'count'},
				{text:'分配予',xtype:'templatecolumn',dataIndex:'after',minWidth:160,flex:1,tpl:'{after_team_name} · {after_namecn}'},
				{text:'分配日期',dataIndex:'effectivedate',xtype:'datecolumn',width:100},
				{text:'操作时间',dataIndex:'time',xtype:'datecolumn',format:'Y-m-d H:i A',width:160},
				{text:'操作人',dataIndex:'operator',width:100}
			],
			features:[{ftype:'grouping'}]
		}		
	]
});
