Ext.define('APP.view.hr.staff.activity.voteActiveForm',{
	extend:'Ext.form.Panel',
	xtype:'hrStaffActivityVoteActiveForm',
    controller:'hr.staff.activity',
    title:'活动信息',
	frame:false,
	defaults:{
		xtype:'fieldset',
		layout:'column',
		defaults:{
			xtype:'container',
			flex:1,
			layout:'anchor'
		}
	},
	items:[
		{columnWidth:1,title:'投票控制',items:[
			{columnWidth:.47,items:[
				{fieldLabel:'投票范围',emptyText:'投票范围',xtype:'comboCompanyDepartment',name:'scope'}
			]},
			{columnWidth:.53,items:[
				{fieldLabel:'多选控制',emptyText:'多选控制',xtype:'combo',name:'control',allowBlank:true,
					store:{
						fields:['value','display'],
						data:[
							[1,'单选'],
							[2,'多选-两票'],
							[3,'多选-三票'],
							[4,'多选-四票'],
							[5,'多选-五票'],
							[6,'多选-六票'],
							[7,'多选-七票'],
							[8,'多选-八票'],
							[9,'多选-九票'],
							[10,'多选-十票']
						]
					},
					width:120,
					valueField:'value',
					displayField:'display'
				}
			]}
		]},
		{columnWidth:1,title:'活动管理',items:[
			{columnWidth:.5,items:[{fieldLabel:'活动名称',emptyText:'活动名称',xtype:'textfield',name:'name'}]},
			{columnWidth:1,items:[{fieldLabel:'活动描述',emptyText:'描述',xtype:'textarea',height:60,name:'explain'}]}
		]}
	]
			
});
