Ext.define('APP.view.sd.sales.track.trend',{
    extend:'Ext.Panel',
    controller:'sd',
	layout:{type:'border',align:'stretch',padding:3},
	defaults:{xtype:'panel',layout:'fit',split:true,border:true},
	viewModel:true,
	dockedItems:[
		{dock:'top',xtype:'toolbar',items:[
			{xtype:'searchbar',
				fields:[
					{xtype:'datepartfield',name:'datepart',value:'month',allowBlank:false},
					{emptyText:'团队...',xtype:'comboCompanyTeam',name:'teamid'},
					{emptyText:'销售...',xtype:'comboCompanyStaff',root:103,name:'staffid'}
				]
			},
			'->',
			{xtype:'refreshbutton'}
		]}
	],
	items:[
		{xtype:'grid',region:'west',iconCls:'f-mt mt-grid',width:480,maxWidth:800,collapsible:true,title:'数据报表',
			store:{
				type:'sales.analysis.sales',
				autoLoad:false,
				sorters:[{property:'objects',direction:'ASC'}],
				proxy:{
					extraParams:{
						datepart:'month',
						startdate:Ext.Date.format(Ext.Date.add(new Date(),Ext.Date.MONTH,-11),'Y-m'),
						enddate:Ext.Date.format(new Date(),'Y-m')
					}
				}
			},
			multiSelect:false,
			dockedItems:[
				{dock:'top',xtype:'toolbar',
					items:[
						'->',
						{xtype:'reconfigurebutton',
							items:[
								{text:'电资销售',value:'resources',pressed:true},
								{text:'客户维护',value:'care'},
								{text:'通话记录',value:'call'}
							]
						},
						'->'
					]
				}
			],
			config:{
				columns:{
					resources:[
						{xtype:'rownumberer'},
						{text:'时间',bind:{text:'{datepart.value:datepartName}'},dataIndex:'objects',minWidth:70,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'无效',dataIndex:'resources_invalid',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'无意向',dataIndex:'resources_no',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'待跟进',dataIndex:'resources_yes',align:'right',tdCls:'x-ui-text-green',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'小计',dataIndex:'resources',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'}
					],
					care:[
						{xtype:'rownumberer'},
						{text:'时间',bind:{text:'{datepart.value:datepartName}'},dataIndex:'objects',minWidth:70,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'无效',dataIndex:'care_invalid',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'无意向',dataIndex:'care_no',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'待跟进',dataIndex:'care_yes',align:'right',tdCls:'x-ui-text-green',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						{text:'小计',dataIndex:'care',align:'right',width:80,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'}
					],
					call:[
						{xtype:'rownumberer'},
						{text:'时间',bind:{text:'{datepart.value:datepartName}'},dataIndex:'objects',minWidth:80,flex:1,renderer:'returnLedgerDay',summaryType:'count'},
						{text:'通话次数',dataIndex:'call_count',align:'right',width:100,renderer:'returnInt',summaryType:'sum',summaryRenderer:'returnInt'},
						//{text:'主叫',dataIndex:'call_duration_caller',align:'right',width:70,renderer:'returnTimeFilter',summaryType:'sum',summaryRenderer:'returnTimeFilter'},
						//{text:'被叫',dataIndex:'call_duration_called',align:'right',width:70,renderer:'returnTimeFilter',summaryType:'sum',summaryRenderer:'returnTimeFilter'},
						//{text:'呼转',dataIndex:'call_duration_transfer',align:'right',width:70,renderer:'returnTimeFilter',summaryType:'sum',summaryRenderer:'returnTimeFilter'},
						{text:'平均时长',dataIndex:'call_duration_average',tdCls:'x-ui-text-green',align:'right',width:120,renderer:'returnTimeFilter',summaryType:'average',summaryRenderer:'returnTimeFilter'},
						{text:'通话时长',dataIndex:'call_duration',tdCls:'x-ui-active x-ui-text-blue',align:'right',width:120,renderer:'returnTimeFilter',summaryType:'sum',summaryRenderer:'returnTimeFilter'}
					]
					
					
				}
			},
			features:[{ftype:'summary',dock:'bottom'}],
			listeners:{
				sortchange:'onMateGridChartSortChange',
				selectionchange:'onMateGridChartSelectionChange'
			}
		},
		{xtype:'mate.chart',mateParameters:{
			type:'trend',
			//renderer:'returnTimeFilterText',
			menu:{
				resources:{
					checked:3,
					items:[
						{text:'无效',field:'resources_invalid',title:'趋势·无效'}, 
						{text:'无意向',field:'resources_no',title:'趋势·无意向'}, 
						{text:'待跟进',field:'resources_yes',title:'趋势·待跟进'}, 
						{text:'小计',field:'resources',title:'趋势·小计'}
					]
				},
				care:{
					checked:3,
					items:[
						{text:'无效',field:'care_invalid',title:'趋势·无效'}, 
						{text:'无意向',field:'care_no',title:'趋势·无意向'}, 
						{text:'待跟进',field:'care_yes',title:'趋势·待跟进'}, 
						{text:'小计',field:'care',title:'趋势·小计'}
					]
				},
				call:{
					checked:2,
					items:[
						{text:'通话次数',field:'call_count',title:'趋势·通话次数'},
						{text:'平均时长',field:'call_duration_average',direction:'趋势·平均时长'},
						{text:'通话时长',field:'call_duration',direction:'趋势·通话时长'}
					]
				}
			}
		}}
	]
});
