Ext.define('APP.view.rd.settings.quoted',{
    extend:'Ext.Panel',
    controller:'rd.monitor',
	layout:{type:'border',align:'stretch',padding:3},
	defaults:{split:false,border:true},
	items:[
		{xtype:'grid',region:'center',title:'商品库',flex:.5,
			reference:'gridBase',
			store:{
				type:'cross',
				autoLoad:true,
				fields:[],
				pageSize:false,
				sorters:[{property:'symbol',direction:'ASC'}],
				proxy:{
					url:Boot.appUrl('/rd/settings/getQuoted.do'),
					extraParams:{}
				}
			},
			viewConfig:{
				stripeRows:true,
				enableTextSelection:true
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]}
			],
			columns:[
				{xtype:'rownumberer'},
				{text:'ID',dataIndex:'id',width:80,hidden:true},
				{text:'商品',dataIndex:'symbol',width:140,summaryType:'count'},
				{text:'商品',dataIndex:'symbol',width:140},
				{text:'商品',dataIndex:'symbol',width:140},
				{text:'商品',dataIndex:'symbol',width:140}
			],
			features:[{ftype:'groupingsummary'},{ftype:'summary',dock:'bottom'}],
			listeners:{
				itemdblclick:'onChangeSymbolClick'
			}
	   	},
		{xtype:'grid',region:'east',title:'被监控的商品配置信息',flex:.5,collapsible:true,margin:'0 0 0 3',
			reference:'gridChange',
			store:{
				autoLoad:true,
				fields:[],
				pageSize:false,
				sorters:[{property:'symbol',direction:'ASC'}],
				proxy:{
					url:Boot.appUrl('/rd/settings/getQuoted.do'),
					extraParams:{}
				}
			},
			dockedItems:[
				{dock:'top',xtype:'toolbar',items:[
					{xtype:'searchbar',
						fields:[
							{emptyText:'关键字...',xtype:'textfield',name:'query',width:140}
						]
					},
					'->',
					{xtype:'refreshbutton'}
				]}
			],
			columns:[
				{xtype:'rownumberer'},
				{text:'商品',dataIndex:'symbol',width:140,summaryType:'count'},
				{text:'别名',dataIndex:'aliases',width:200},
				{text:'阈值',dataIndex:'repeat',width:100,align:'right'},
				{text:'通知方式',dataIndex:'notice_type',width:100,summaryType:'sum'},
				{text:'通知对象',dataIndex:'notice_userid',width:200},
				{text:'注释',dataIndex:'explain',minWidth:300,renderer:'returnMore'},
				{xtype:'actioncolumn',text:'配置',tooltip:'配置报警规则',align:'center',width:60,iconCls:'f-mt mt-action-settings',handler:'onQuotedUpdateClick'},
				{xtype:'actioncolumn',text:'修改',tooltip:'修改',align:'center',width:60,iconCls:'f-mt mt-action-update',handler:'onQuotedUpdateClick'}
			],
			features:[{ftype:'summary',dock:'bottom'}]
		}		
	]
});
