Ext.define('APP.view.ia.system.account.basis',{
    extend:'Ext.form.Panel',
    controller:'ia.system.account',
	width:880,
	items:[
		{title:'分类策略',fieldDefaults:{allowBlank:false},items:[
			{columnWidth:1,items:[{fieldLabel:'分类策略',xtype:'radiogroup',columns:8,
				items:[
					{boxLabel:'组',name:'template_switch',inputValue:'1',reference:'enableGroupSwitch',checked:true},
					{boxLabel:'账户',name:'template_switch',inputValue:'2',reference:'enableAccountSwitch'},
					{boxLabel:'禁用',name:'template_switch',inputValue:'0'}
				]
			}]}
		]},
		{title:'模拟账户',fieldDefaults:{allowBlank:false},items:[
			{columnWidth:.25,items:[
				{fieldLabel:'默认组',xtype:'textfield',name:'demo_group'}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'账号模板',xtype:'textfield',name:'demo_account_template',bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'当日递增',xtype:'numberfield',minValue:1,name:'demo_account_today_plus',step:1,hideTrigger:false,bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:1,items:[
				{fieldLabel:'功能控制',xtype:'checkboxarraygroup',layout:'vbox',name:'demo_control',allowBlank:true,
					defaults:{xtype:'container',layout:'hbox',defaults:{xtype:'checkbox',width:100}},
					items:[
						{items:[
							{boxLabel:'需效验码'}
						]},
						{items:[
							{boxLabel:'短信通知'},
							{boxLabel:'邮件通知'},
							{boxLabel:'微信通知'}
						]}
					]
				}
			]}
		]},
		{title:'真实账户',fieldDefaults:{allowBlank:false},items:[
			{columnWidth:1,items:[
				{fieldLabel:'组模板',xtype:'comboAccountGroups',name:'real_group_template',bind:{hidden:'{!enableGroupSwitch.checked}',disabled:'{!enableGroupSwitch.checked}'}},
				{fieldLabel:'账号模板',xtype:'textfield',name:'real_account_template',bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'默认组',xtype:'comboAccountGroup',name:'real_group'}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'当日递增',xtype:'numberfield',minValue:1,name:'real_account_today_plus',step:1,hideTrigger:false,bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'隔天递增',xtype:'numberfield',minValue:0,name:'real_account_nextday_plus',step:1,hideTrigger:false,bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'默认权限',xtype:'comboAccountRole',name:'real_roleid'}	
			]},
			{columnWidth:1,items:[
				{fieldLabel:'功能控制',xtype:'checkboxarraygroup',layout:'vbox',name:'real_control',allowBlank:true,
					defaults:{xtype:'container',layout:'hbox',defaults:{xtype:'checkbox',width:100}},
					items:[
						{items:[
							{boxLabel:'需效验码'},
							{boxLabel:'需要审核'}
						]},
						{items:[
							{boxLabel:'短信通知'},
							{boxLabel:'邮件通知'},
							{boxLabel:'微信通知'}
						]}
					]
				}
			]}
		]},
		{title:'代理账户',fieldDefaults:{allowBlank:false},items:[
			{columnWidth:1,items:[
				{fieldLabel:'组模板',xtype:'comboAccountGroups',name:'agent_group_template',bind:{hidden:'{!enableGroupSwitch.checked}',disabled:'{!enableGroupSwitch.checked}'}},
				{fieldLabel:'账号模板',xtype:'textfield',name:'agent_account_template',bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'默认组',xtype:'comboAccountGroup',name:'agent_group'}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'当日递增',xtype:'numberfield',minValue:1,name:'agent_account_today_plus',step:1,hideTrigger:false,bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'隔天递增',xtype:'numberfield',minValue:0,name:'agent_account_nextday_plus',step:1,hideTrigger:false,bind:{hidden:'{!enableAccountSwitch.checked}',disabled:'{!enableAccountSwitch.checked}'}}
			]},
			{columnWidth:.25,items:[
				{fieldLabel:'默认权限',xtype:'comboAccountRole',name:'agent_roleid'}	
			]},
			{columnWidth:1,items:[
				{fieldLabel:'功能控制',xtype:'checkboxarraygroup',layout:'vbox',name:'agent_control',allowBlank:true,
					defaults:{xtype:'container',layout:'hbox',defaults:{xtype:'checkbox',width:100}},
					items:[
						{items:[
							{boxLabel:'需效验码'},
							{boxLabel:'需要审核'}
						]},
						{items:[
							{boxLabel:'短信通知'},
							{boxLabel:'邮件通知'},
							{boxLabel:'微信通知'}
						]}
					]
				}
			]}
		]},
		{title:'其它',collapsed:true,items:[
			{columnWidth:1,defaults:{xtype:'checkboxarraygroup',layout:'hbox',allowBlank:true,defaults:{xtype:'checkbox',width:100}},items:[
				{fieldLabel:'资料更改',xtype:'checkboxarraygroup',layout:'vbox',name:'update_control',
					defaults:{xtype:'container',layout:'hbox',defaults:{xtype:'checkbox',width:100}},
					items:[
						{items:[
							{boxLabel:'需效验码'},
							{boxLabel:'需要审核'}
						]},
						{items:[
							{boxLabel:'短信通知'},
							{boxLabel:'邮件通知'},
							{boxLabel:'微信通知'}
						]}
					]
				},
				{fieldLabel:'证件',name:'credentials_control',items:[
					{boxLabel:'身份证(正)'},
					{boxLabel:'身份证(反)'},
					{boxLabel:'银行卡(正)'},
					{boxLabel:'银行卡(反)'}
				]}
			]},
			{columnWidth:.67,items:[
				{fieldLabel:'杠杆',xtype:'textfield',name:'leverage_control'}
			]}
		]},
		{title:'MT4 账户表字段对应',collapsed:true,fieldDefaults:{allowBlank:true,emptyText:'N/A'},items:[
			{columnWidth:.34,items:[
				{fieldLabel:'名称',xtype:'comboAccountField',name:'field_name'},
				{fieldLabel:'国家',xtype:'comboAccountField',name:'field_country'},
				{fieldLabel:'地址',xtype:'comboAccountField',name:'field_address'}
			]},
			{columnWidth:.33,items:[
				{fieldLabel:'电话',xtype:'comboAccountField',name:'field_phone'},
				{fieldLabel:'州/省',xtype:'comboAccountField',name:'field_state'},
				{fieldLabel:'邮编',xtype:'comboAccountField',name:'field_zipcode'}
			]},
			{columnWidth:.33,items:[
				{fieldLabel:'电子邮件',xtype:'comboAccountField',name:'field_email'},
				{fieldLabel:'城市',xtype:'comboAccountField',name:'field_city'},
				{fieldLabel:'ID 号码',xtype:'comboAccountField',name:'field_id'}
			]}
		]}
	],
	mateParameters:{
		url:Boot.appUrl('/sd/system/settings/getAccount.do')
	},
	listeners:{afterrender:'onMateFormLoadData'},
	buttons:['->',
		{text:'保存信息',iconCls:'f-mt mt-button-submit',scale:'medium',
			mateParameters:{
				url:Boot.appUrl('/sd/system/settings/updateAccount.do')
			},
			handler:'onMateFormSubmit'
		},
		{text:'取消操作',iconCls:'f-mt mt-button-cancel',scale:'medium',handler:'onMateWindowDestroy'}
	]
});
